#!/bin/bash

# Colors Setup
Color_Off='\033[0m'
White="\e[1;97m"
Blue="\033[1;34m"
Bg_Red="\e[41m"
Bg_Green="\e[42m"
Bg_Error="${Bg_Red}${White}"
Bg_Success="${Bg_Green}${White}"

# Package
echo -e "${Blue}------------------>> Running package <<------------------${Color_Off}"
./mvnw clean package -Dmaven.test.skip=true

# Checkstyle
echo -e ""
echo -e "${Blue}------------------>> Running CheckStyle <<------------------${Color_Off}"
./mvnw checkstyle:checkstyle

# Verify if checkstyle performed successfully
rc=$?
if [ $rc -ne 0 ]; then
  echo -e "${Bg_Error}Failed CheckStyle!${Color_Off}"
  exit 1
fi

echo -e "${Bg_Success}CheckStyle executed successfully!${Color_Off}"

# Unit Tests
echo -e ""
echo -e "${Blue}------------------>> Running Unit Tests <<------------------${Color_Off}"
./mvnw test -Punit-tests

# Verify if mvn test performed successfully
rc=$?
if [ $rc -ne 0 ]; then
  echo -e "${Bg_Error}Failed Unit Tests!${Color_Off}"
  exit 1
fi

echo -e "${Bg_Success}Unit Tests executed successfully!${Color_Off}"

# Integration Tests
echo -e ""
echo -e "${Blue}------------------>> Running Integration Tests <<------------------${Color_Off}"
./mvnw test -Pintegration-tests

# Verify if mvn test performed successfully
rc=$?
if [ $rc -ne 0 ]; then
  echo -e "${Bg_Error}Failed Integration Tests!${Color_Off}"
  exit 1
fi

echo -e "${Bg_Success}Integration Tests executed successfully!${Color_Off}"

echo -e ""
echo -e "${Bg_Success}Validation completed!${Color_Off}"
